server:
  port: 8080

spring:
  application:
    name: ComNCheck
  config:
    import:
      - classpath:/yaml/application-dev.yaml
      - classpath:/yaml/application-local.yaml
  profiles:
    group:
      setting: local, log
    active : setting

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:/gcp/ancient-pipe-447417-i4-755ce59fbf03.json
        project-id: ${GCP_PROJECT_ID}
        bucket: ${GCP_BUCKET_ID}
      firestore:
        project-id: ${FIREBASE_PROJECT_ID}
        credentials:
          location: classpath:/firebase/comncheck-firebase-adminsdk-fbsvc-1255c6f2ed.json


  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATIONMS}
