server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: ComNCheck
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_DB_URL:jdbc:h2:mem:test} #url: 'jdbc:h2:~/test' -> H2 DB 연결 주소 (Embedded Mode)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:ancient-pipe-447417-i4-755ce59fbf03.json
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET_ID}
jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATIONMS}