spring:
  config:
    activate:
      on-profile: log
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

logging.level:
  org.hibernate:
    type: trace
    orm:
      jdbc:
        bind: trace