spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_DB_URL:jdbc:h2:mem:test} #url: 'jdbc:h2:~/test' -> H2 DB 연결 주소 (Embedded Mode)
    username: ${H2_DB_USERNAME}
    password: ${H2_DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging.level:
  org.hibernate:
    type: trace
    orm:
      jdbc:
        bind: trace